package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"

	"github.com/steph-dm/MyUta/backend/internal/graph/dataloader"
	"github.com/steph-dm/MyUta/backend/internal/service"
	"github.com/steph-dm/MyUta/backend/internal/storage"
	"github.com/steph-dm/MyUta/backend/pkg/apperror"
	"github.com/steph-dm/MyUta/backend/pkg/auth"
	"github.com/steph-dm/MyUta/backend/pkg/middleware"
	"github.com/steph-dm/MyUta/backend/pkg/scalar"
	"github.com/steph-dm/MyUta/backend/pkg/validator"
	"github.com/steph-dm/MyUta/backend/pkg/youtube"
)

// Songs is the resolver for the songs field.
func (r *artistResolver) Songs(ctx context.Context, obj *storage.Artist) ([]*storage.Song, error) {
	if obj.LoadedSongs != nil {
		return obj.LoadedSongs, nil
	}
	userID := auth.UserIDFromContext(ctx)
	if userID == "" {
		return nil, nil
	}
	return r.SongService.ListByArtist(ctx, userID, obj.ID)
}

// SongCount is the resolver for the songCount field.
func (r *artistResolver) SongCount(ctx context.Context, obj *storage.Artist) (int, error) {
	if obj.SongCount != nil {
		return *obj.SongCount, nil
	}
	if obj.LoadedSongs != nil {
		return len(obj.LoadedSongs), nil
	}
	userID := auth.UserIDFromContext(ctx)
	return r.SongService.CountByArtist(ctx, userID, obj.ID)
}

// IsFavorite is the resolver for the isFavorite field.
func (r *artistResolver) IsFavorite(ctx context.Context, obj *storage.Artist) (*bool, error) {
	userID := auth.UserIDFromContext(ctx)
	if userID == "" {
		return nil, nil
	}
	result, err := dataloader.For(ctx).FavoriteArtist.Load(ctx, obj.ID)()
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, email string, password string, name string, birthdate scalar.DateTime) (*storage.AuthPayload, error) {
	payload, err := r.AuthService.Register(ctx, middleware.ClientIPFromContext(ctx, HTTPRequestKey), email, password, name, birthdate)
	if err != nil {
		return nil, err
	}
	SetTokenCookie(ctx, payload.Token, r.SecureCookie)
	return payload, nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, email string, password string) (*storage.AuthPayload, error) {
	payload, err := r.AuthService.Login(ctx, middleware.ClientIPFromContext(ctx, HTTPRequestKey), email, password)
	if err != nil {
		return nil, err
	}
	SetTokenCookie(ctx, payload.Token, r.SecureCookie)
	return payload, nil
}

// Logout is the resolver for the logout field.
func (r *mutationResolver) Logout(ctx context.Context) (bool, error) {
	ClearTokenCookie(ctx, r.SecureCookie)
	return true, nil
}

// RefreshToken is the resolver for the refreshToken field.
func (r *mutationResolver) RefreshToken(ctx context.Context) (*storage.AuthPayload, error) {
	userID, err := auth.RequireAuth(auth.UserIDFromContext(ctx))
	if err != nil {
		return nil, err
	}
	if err := r.RateLimiter.Check("refresh:"+userID, 10, 3600); err != nil {
		return nil, apperror.Forbidden(err.Error())
	}
	payload, err := r.AuthService.RefreshToken(ctx, userID)
	if err != nil {
		return nil, err
	}
	SetTokenCookie(ctx, payload.Token, r.SecureCookie)
	return payload, nil
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, id string, email *string, name *string, birthdate *scalar.DateTime, defaultMachineType *storage.MachineType) (*storage.User, error) {
	userID, err := auth.RequireAuth(auth.UserIDFromContext(ctx))
	if err != nil {
		return nil, err
	}
	return r.UserService.UpdateUser(ctx, userID, id, email, name, birthdate, defaultMachineType)
}

// UpsertArtist is the resolver for the upsertArtist field.
func (r *mutationResolver) UpsertArtist(ctx context.Context, name string) (*storage.Artist, error) {
	userID, err := auth.RequireAuth(auth.UserIDFromContext(ctx))
	if err != nil {
		return nil, err
	}
	return r.ArtistService.UpsertArtist(ctx, userID, name)
}

// UpdateArtist is the resolver for the updateArtist field.
func (r *mutationResolver) UpdateArtist(ctx context.Context, id string, name string) (*storage.Artist, error) {
	userID, err := auth.RequireAuth(auth.UserIDFromContext(ctx))
	if err != nil {
		return nil, err
	}
	return r.ArtistService.UpdateArtist(ctx, userID, id, name)
}

// UpsertSong is the resolver for the upsertSong field.
func (r *mutationResolver) UpsertSong(ctx context.Context, id *string, title string, artistID string, genres []storage.Genre, youtubeURL *string, generatedYoutube *bool) (*storage.Song, error) {
	userID, err := auth.RequireAuth(auth.UserIDFromContext(ctx))
	if err != nil {
		return nil, err
	}
	return r.SongService.UpsertSong(ctx, userID, id, title, artistID, genres, youtubeURL, generatedYoutube)
}

// UpsertReview is the resolver for the upsertReview field.
func (r *mutationResolver) UpsertReview(ctx context.Context, id *string, songID string, date scalar.DateTime, score float64, machineType storage.MachineType, issues []storage.Issue, notes *string) (*storage.Review, error) {
	userID, err := auth.RequireAuth(auth.UserIDFromContext(ctx))
	if err != nil {
		return nil, err
	}
	return r.ReviewService.UpsertReview(ctx, userID, id, songID, date, score, machineType, issues, notes)
}

// DeleteSong is the resolver for the deleteSong field.
func (r *mutationResolver) DeleteSong(ctx context.Context, id string) (*storage.Song, error) {
	userID, err := auth.RequireAuth(auth.UserIDFromContext(ctx))
	if err != nil {
		return nil, err
	}
	return r.SongService.DeleteSong(ctx, userID, id)
}

// DeleteArtist is the resolver for the deleteArtist field.
func (r *mutationResolver) DeleteArtist(ctx context.Context, id string) (*storage.Artist, error) {
	userID, err := auth.RequireAuth(auth.UserIDFromContext(ctx))
	if err != nil {
		return nil, err
	}
	return r.ArtistService.DeleteArtist(ctx, userID, id)
}

// DeleteReview is the resolver for the deleteReview field.
func (r *mutationResolver) DeleteReview(ctx context.Context, id string) (*storage.Review, error) {
	userID, err := auth.RequireAuth(auth.UserIDFromContext(ctx))
	if err != nil {
		return nil, err
	}
	return r.ReviewService.DeleteReview(ctx, userID, id)
}

// ToggleFavorite is the resolver for the toggleFavorite field.
func (r *mutationResolver) ToggleFavorite(ctx context.Context, songID string) (bool, error) {
	userID, err := auth.RequireAuth(auth.UserIDFromContext(ctx))
	if err != nil {
		return false, err
	}
	return r.SongService.ToggleFavorite(ctx, userID, songID)
}

// ToggleFavoriteArtist is the resolver for the toggleFavoriteArtist field.
func (r *mutationResolver) ToggleFavoriteArtist(ctx context.Context, artistID string) (bool, error) {
	userID, err := auth.RequireAuth(auth.UserIDFromContext(ctx))
	if err != nil {
		return false, err
	}
	return r.ArtistService.ToggleFavorite(ctx, userID, artistID)
}

// ChangePassword is the resolver for the changePassword field.
func (r *mutationResolver) ChangePassword(ctx context.Context, currentPassword string, newPassword string) (bool, error) {
	userID, err := auth.RequireAuth(auth.UserIDFromContext(ctx))
	if err != nil {
		return false, err
	}
	if err := r.RateLimiter.Check("chgpwd:"+userID, 5, 3600); err != nil {
		return false, apperror.Forbidden(err.Error())
	}
	return r.AuthService.ChangePassword(ctx, userID, currentPassword, newPassword)
}

// DeleteReviews is the resolver for the deleteReviews field.
func (r *mutationResolver) DeleteReviews(ctx context.Context, ids []string) (int, error) {
	userID, err := auth.RequireAuth(auth.UserIDFromContext(ctx))
	if err != nil {
		return 0, err
	}
	if err := validator.BatchSize(ids); err != nil {
		return 0, err
	}
	return r.ReviewService.DeleteReviews(ctx, userID, ids)
}

// DeleteAccount is the resolver for the deleteAccount field.
func (r *mutationResolver) DeleteAccount(ctx context.Context, password string) (bool, error) {
	userID, err := auth.RequireAuth(auth.UserIDFromContext(ctx))
	if err != nil {
		return false, err
	}
	if err := r.RateLimiter.Check("delacc:"+userID, 3, 3600); err != nil {
		return false, apperror.Forbidden(err.Error())
	}
	return r.AuthService.DeleteAccount(ctx, userID, password)
}

// ExtractReviewFromImage is the resolver for the extractReviewFromImage field.
func (r *mutationResolver) ExtractReviewFromImage(ctx context.Context, imageBase64 string) (*service.ExtractedReview, error) {
	userID, err := auth.RequireAuth(auth.UserIDFromContext(ctx))
	if err != nil {
		return nil, err
	}
	if err := r.RateLimiter.Check("ocr:"+userID, 10, 3600); err != nil {
		return nil, apperror.Forbidden(err.Error())
	}
	if imageBase64 == "" {
		return nil, apperror.BadInput("No image provided", "imageBase64")
	}
	if len(imageBase64) > 10*1024*1024 {
		return nil, apperror.BadInput("Image too large. Maximum size is 10MB.", "imageBase64")
	}
	if r.OCR == nil {
		return nil, apperror.Internal("Anthropic API key not configured")
	}
	return r.OCR.ExtractReview(ctx, imageBase64)
}

// ImportData is the resolver for the importData field.
func (r *mutationResolver) ImportData(ctx context.Context, jsonData string) (*storage.ImportResult, error) {
	userID, err := auth.RequireAuth(auth.UserIDFromContext(ctx))
	if err != nil {
		return nil, err
	}
	if err := r.RateLimiter.Check("import:"+userID, 5, 3600); err != nil {
		return nil, apperror.Forbidden(err.Error())
	}
	if err := validator.ImportSize(jsonData); err != nil {
		return nil, err
	}
	return r.ExportService.ImportData(ctx, userID, jsonData)
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*storage.User, error) {
	userID, err := auth.RequireAuth(auth.UserIDFromContext(ctx))
	if err != nil {
		return nil, err
	}
	return r.UserService.Me(ctx, userID)
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*storage.User, error) {
	userID, err := auth.RequireAuth(auth.UserIDFromContext(ctx))
	if err != nil {
		return nil, err
	}
	return r.UserService.ListUsers(ctx, userID)
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*storage.User, error) {
	userID, err := auth.RequireAuth(auth.UserIDFromContext(ctx))
	if err != nil {
		return nil, err
	}
	return r.UserService.GetUser(ctx, userID, id)
}

// Artists is the resolver for the artists field.
func (r *queryResolver) Artists(ctx context.Context, take *int, skip *int) ([]*storage.Artist, error) {
	userID, err := auth.RequireAuth(auth.UserIDFromContext(ctx))
	if err != nil {
		return nil, err
	}
	if err := validator.Pagination(take, skip); err != nil {
		return nil, err
	}
	return r.ArtistService.ListArtists(ctx, userID, take, skip)
}

// Artist is the resolver for the artist field.
func (r *queryResolver) Artist(ctx context.Context, id string) (*storage.Artist, error) {
	userID, err := auth.RequireAuth(auth.UserIDFromContext(ctx))
	if err != nil {
		return nil, err
	}
	return r.ArtistService.GetArtistWithSongs(ctx, userID, id)
}

// Songs is the resolver for the songs field.
func (r *queryResolver) Songs(ctx context.Context, take *int, skip *int) ([]*storage.Song, error) {
	userID, err := auth.RequireAuth(auth.UserIDFromContext(ctx))
	if err != nil {
		return nil, err
	}
	if err := validator.Pagination(take, skip); err != nil {
		return nil, err
	}
	return r.SongService.ListSongs(ctx, userID, take, skip)
}

// Song is the resolver for the song field.
func (r *queryResolver) Song(ctx context.Context, id string) (*storage.Song, error) {
	userID, err := auth.RequireAuth(auth.UserIDFromContext(ctx))
	if err != nil {
		return nil, err
	}
	return r.SongService.GetSong(ctx, userID, id)
}

// Reviews is the resolver for the reviews field.
func (r *queryResolver) Reviews(ctx context.Context) ([]*storage.Review, error) {
	userID, err := auth.RequireAuth(auth.UserIDFromContext(ctx))
	if err != nil {
		return nil, err
	}
	return r.ReviewService.ListReviews(ctx, userID)
}

// Review is the resolver for the review field.
func (r *queryResolver) Review(ctx context.Context, id string) (*storage.Review, error) {
	userID, err := auth.RequireAuth(auth.UserIDFromContext(ctx))
	if err != nil {
		return nil, err
	}
	return r.ReviewService.GetReview(ctx, userID, id)
}

// MyReviews is the resolver for the myReviews field.
func (r *queryResolver) MyReviews(ctx context.Context, userID string) ([]*storage.ReviewWithSong, error) {
	currentUserID, err := auth.RequireAuth(auth.UserIDFromContext(ctx))
	if err != nil {
		return nil, err
	}
	return r.ReviewService.MyReviews(ctx, currentUserID, userID)
}

// ReviewsBySong is the resolver for the reviewsBySong field.
func (r *queryResolver) ReviewsBySong(ctx context.Context, songID string) ([]*storage.ReviewWithSong, error) {
	userID, err := auth.RequireAuth(auth.UserIDFromContext(ctx))
	if err != nil {
		return nil, err
	}
	return r.ReviewService.ReviewsBySong(ctx, userID, songID)
}

// RecentReviews is the resolver for the recentReviews field.
func (r *queryResolver) RecentReviews(ctx context.Context, days *int) ([]*storage.ReviewWithSong, error) {
	userID, err := auth.RequireAuth(auth.UserIDFromContext(ctx))
	if err != nil {
		return nil, err
	}
	if err := validator.Days(days); err != nil {
		return nil, err
	}
	return r.ReviewService.RecentReviews(ctx, userID, days)
}

// SearchYoutube is the resolver for the searchYoutube field.
func (r *queryResolver) SearchYoutube(ctx context.Context, artist string, song string) ([]*youtube.Result, error) {
	userID, err := auth.RequireAuth(auth.UserIDFromContext(ctx))
	if err != nil {
		return nil, err
	}
	if err := r.RateLimiter.Check("youtube:"+userID, 30, 3600); err != nil {
		return nil, apperror.Forbidden(err.Error())
	}
	if r.YouTube == nil {
		return nil, apperror.Internal("YouTube API key not configured")
	}
	return r.YouTube.Search(ctx, artist, song)
}

// SongWithReviews is the resolver for the songWithReviews field.
func (r *queryResolver) SongWithReviews(ctx context.Context, id string) (*storage.Song, error) {
	userID, err := auth.RequireAuth(auth.UserIDFromContext(ctx))
	if err != nil {
		return nil, err
	}
	return r.ReviewService.SongWithReviews(ctx, userID, id)
}

// MyFavorites is the resolver for the myFavorites field.
func (r *queryResolver) MyFavorites(ctx context.Context) ([]*storage.Song, error) {
	userID, err := auth.RequireAuth(auth.UserIDFromContext(ctx))
	if err != nil {
		return nil, err
	}
	return r.SongService.MyFavorites(ctx, userID)
}

// MyFavoriteArtists is the resolver for the myFavoriteArtists field.
func (r *queryResolver) MyFavoriteArtists(ctx context.Context) ([]*storage.Artist, error) {
	userID, err := auth.RequireAuth(auth.UserIDFromContext(ctx))
	if err != nil {
		return nil, err
	}
	return r.ArtistService.MyFavoriteArtists(ctx, userID)
}

// ExportData is the resolver for the exportData field.
func (r *queryResolver) ExportData(ctx context.Context) (string, error) {
	userID, err := auth.RequireAuth(auth.UserIDFromContext(ctx))
	if err != nil {
		return "", err
	}
	return r.ExportService.ExportData(ctx, userID)
}

// DashboardStats is the resolver for the dashboardStats field.
func (r *queryResolver) DashboardStats(ctx context.Context) (*storage.DashboardStats, error) {
	userID, err := auth.RequireAuth(auth.UserIDFromContext(ctx))
	if err != nil {
		return nil, err
	}
	return r.ReviewService.DashboardStats(ctx, userID)
}

// User is the resolver for the user field.
func (r *reviewResolver) User(ctx context.Context, obj *storage.Review) (*storage.User, error) {
	if obj.LoadedUser != nil {
		return obj.LoadedUser, nil
	}
	callerID := auth.UserIDFromContext(ctx)
	if callerID == "" || callerID != obj.UserID {
		return nil, nil
	}
	return r.UserService.GetUserByID(ctx, obj.UserID)
}

// User is the resolver for the user field.
func (r *reviewWithSongResolver) User(ctx context.Context, obj *storage.ReviewWithSong) (*storage.User, error) {
	if obj.LoadedUser != nil {
		return obj.LoadedUser, nil
	}
	callerID := auth.UserIDFromContext(ctx)
	if callerID == "" || callerID != obj.UserID {
		return nil, nil
	}
	return r.UserService.GetUserByID(ctx, obj.UserID)
}

// Song is the resolver for the song field.
func (r *reviewWithSongResolver) Song(ctx context.Context, obj *storage.ReviewWithSong) (*storage.Song, error) {
	if obj.LoadedSong != nil {
		return obj.LoadedSong, nil
	}
	userID := auth.UserIDFromContext(ctx)
	return r.SongService.GetSong(ctx, userID, obj.SongID)
}

// Artist is the resolver for the artist field.
func (r *songResolver) Artist(ctx context.Context, obj *storage.Song) (*storage.Artist, error) {
	if obj.LoadedArtist != nil {
		return obj.LoadedArtist, nil
	}
	return r.ArtistService.GetArtist(ctx, obj.ArtistID)
}

// ReviewCount is the resolver for the reviewCount field.
func (r *songResolver) ReviewCount(ctx context.Context, obj *storage.Song) (int, error) {
	if obj.ReviewCount != nil {
		return *obj.ReviewCount, nil
	}
	if obj.LoadedReviews != nil {
		return len(obj.LoadedReviews), nil
	}
	userID := auth.UserIDFromContext(ctx)
	return r.ReviewService.ReviewCount(ctx, userID, obj.ID)
}

// Reviews is the resolver for the reviews field.
func (r *songResolver) Reviews(ctx context.Context, obj *storage.Song) ([]*storage.ReviewWithSong, error) {
	if obj.LoadedReviews != nil {
		return obj.LoadedReviews, nil
	}
	userID := auth.UserIDFromContext(ctx)
	if userID == "" {
		return nil, nil
	}
	return r.ReviewService.ReviewsBySong(ctx, userID, obj.ID)
}

// IsFavorite is the resolver for the isFavorite field.
func (r *songResolver) IsFavorite(ctx context.Context, obj *storage.Song) (*bool, error) {
	userID := auth.UserIDFromContext(ctx)
	if userID == "" {
		return nil, nil
	}
	result, err := dataloader.For(ctx).FavoriteSong.Load(ctx, obj.ID)()
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Reviews is the resolver for the reviews field.
func (r *userResolver) Reviews(ctx context.Context, obj *storage.User) ([]*storage.Review, error) {
	userID := auth.UserIDFromContext(ctx)
	if userID == "" || userID != obj.ID {
		return nil, apperror.Forbidden("Not authorized to view these reviews")
	}
	return r.ReviewService.ReviewsByUser(ctx, obj.ID)
}

// Artist returns ArtistResolver implementation.
func (r *Resolver) Artist() ArtistResolver { return &artistResolver{r} }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Review returns ReviewResolver implementation.
func (r *Resolver) Review() ReviewResolver { return &reviewResolver{r} }

// ReviewWithSong returns ReviewWithSongResolver implementation.
func (r *Resolver) ReviewWithSong() ReviewWithSongResolver { return &reviewWithSongResolver{r} }

// Song returns SongResolver implementation.
func (r *Resolver) Song() SongResolver { return &songResolver{r} }

// User returns UserResolver implementation.
func (r *Resolver) User() UserResolver { return &userResolver{r} }

type artistResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type reviewResolver struct{ *Resolver }
type reviewWithSongResolver struct{ *Resolver }
type songResolver struct{ *Resolver }
type userResolver struct{ *Resolver }
